// The types for integrating with api that is not generated by the backend team.
// This is a manually written typings, we can safely edit this code.

import type { PackageType } from "./api";

export type SearchPhotographerParams = {
    name?: string;
    location?: string;
    minPrice?: number;
    maxPrice?: number;
    type?: PackageType; 
}